## 1. 사이킷런 소개와 특징
    1) 파이썬 머신러닝 라이브러리 중 가장 많이 사용
    2) 가장 파이썬스러운 API 제공

In [2]:
import sklearn

print(sklearn.__version__)

0.24.1


## 2. 첫 번째 머신러닝 만들어보기 - 붓꽃 품종 예측
    1) 분류 : 대표적인 지도학습 중 하나
       - 지도학습 : 레이블 데이터로 모델 학습 후 미지의 정답 예측
       - 학습 데이터 세트, 테스트 데이터 세트 로 구성

In [5]:
# 사이킷런에서 자체적으로 제공하는 데이터 세트 생성 모듈
from sklearn.datasets import load_iris

# 트리 기반 ML알고리즘 구현 클래스 모임
from sklearn.tree import DecisionTreeClassifier

# 학습,검증 데이터를 분리하거나 최적의 하이퍼파라미터로 평가하기 위한 다양한 모듈의 모임
from sklearn.model_selection import train_test_split

In [7]:
import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris.data는 iris 데이터 세트에서 feature 만으로 된 데이터를 numpy로 가지고 있음(1. feature)
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 numpy로 가지고 있음(2. label)
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 df로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

#### ** feature : sepal length 등 4가지
#### ** label(결정값) : 0,1,2 ( 0:setosa, 1:versicolor, 2:virginica)

### 데이터 세트 분리

In [9]:
# 학습용 데이터와 테스트용 데이터 분리
# test_size = 0.2 -> 전체 데이터 중 테스트 데이터가 20%
# random_state=11 -> 데이터 세트 생성하기 위해 주어지는 난수 발생 값. 지정하지 않으면 수행할 때마다 다른 데이터 만들 수 있음
# (수행할 때마다 동일한 데이터 세트로 분리하려면 일정 숫자 부여)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

### 의사결정트리 이용해 학습과 예측 수행

In [11]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행(train data 이용)
dt_clf.fit(X_train, y_train)

# 학습 완료된 트리 객체에서 테스트데이터 세트로 예측 수행(입력자료 X_test)
pred = dt_clf.predict(X_test)

### 평가

In [12]:
# 예측 성능 평가(출력자료 y_test)
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9333


## 3. 사이킷런의 기반 프레임 워크 익히기
    1) Estimator 클래스 = Classifier + Regressor, 즉 지도학습의 모든 알고리즘 구현한 클래스 통칭해서 Estimator라 함.
        - Classifier : 분류 알고리즘 구현 클래스
        - Regressor : 회귀 알고리즘 구현 클래스
        - estimator 클래스는 fit()과 predict() 내부에서 구현
        
    2) 비지도학습은 fit()과 transform() 적용
        - 여기서 fit()은 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조 맞추는 작업

### 3-1) 내장된 예제 데이터 세트
    1) 데이터 세트는 일반적으로 딕셔너리 형태임. 일반적인 데이터 세트의 key
        - data : feature의 데이터 세트 -> ndarray 타입
        - target : 분류시 레이블값, 회귀시 숫자 결괏값 데이터 세트 -> ndarray 타입
        - target_names : 개별 레이블 이름 -> ndarray 타입 or 파이썬 리스트 타입
        - feature_names : feature 이름 -> ndarray 타입 or 파이썬 리스트 타입
        - DESCR : 데이터 세트에 대한 설명과 각 feature의 설명 -> string

In [15]:
# 붓꽃 데이터 세트 생성
from sklearn.datasets import load_iris
iris_data = load_iris()
print(type(iris_data))

# 데이터 세트의 key값 확인
keys = iris_data.keys()
print(keys)

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


### 3-2) model selection 모듈 소개

#### 1) 학습/데이터 세트 분리 - train_test_split()

In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트로 예측 수행 -> 잘못된 상황 예제(테스트 데이터로 예측 해야함)
pred = dt_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label, pred))

예측 정확도:  1.0


In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
dt_clf = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9556


#### 2) 교차검증
    - 예측 성능을 평가하기 위한 별도의 테스트 데이터를 사용하는 방법은 과적합 문제 발생할 수 있음(고정된 데이터)
    - 이를 개선하기 위해 교차 검증 이용
    - 데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가 수행
    - 기존 학습 데이터 -> 학습데이터set + 검증데이터set
    - 대부분 ML모델 : 1차-교차검증기반, 최종-테스트데이터 세트에 적용해 평가

#### 2-1) K 폴드 교차 검증
    - 가장 보편적
    - K개의 데이터 폴드 세트 만들어 K번만큼 각 폴드 세트에 학습과 검증 평가 반복적으로 수행
    - K개의 데이터 폴드 세트: 데이터 세트를 K개로 분할 -> (학습 폴드 세트 K-1개) + (검증 세트 1개)
    - K=5 경우 예시
        -----------데이터 세트-----------
    1 :  학습   학습   학습   학습  "검증"
    2 :  학습   학습   학습  "검증"  학습
    3 :  학습   학습  "검증"  학습   학습
    4 :  학습  "검증"  학습   학습   학습
    5 : "검증"  학습   학습   학습   학습

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴트 세트별 정확도 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기: ', features.shape[0])

붓꽃 데이터 세트 크기:  150


In [21]:
n_iter = 0

# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
         .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도:  0.9


#### 2-2) Stratified K 폴드
    - 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식
    - 원본 데이터의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트 분배

In [25]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [30]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('\n## 교차검증: {}'.format(n_iter))
    print('\n학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('\n검증 레이블 데이터 분포:\n', label_test.value_counts())


## 교차검증: 1

학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64

## 교차검증: 2

학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64

## 교차검증: 3

학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


#### * 붓꽃 데이터 교차검증

In [43]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요(K 폴드는 features만)
for train_index, test_index in skfold.split(features, label):
    
    # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    # 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 : {1:.4f}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
         .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도: ', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.9800, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.9400, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.9800, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도:  [0.98 0.94 0.98]
## 평균 검증 정확도:  0.9666666666666667


#### 2-3) 교차검증을 보다 간편하게 - cross_val_score()
    1 - cross_val_score(estimator, X, y, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch)
    2 - cross_validata : 여러개의 평가 지표 반환 가능

In [45]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores), 4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


### 3-3) GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
    - 하이퍼 파라미터 : 머신러닝 알고리즘을 구성하는 주요 구성 요소. 이 값을 조정해 알고리즘의 예측 성능을 개선할 수 있음.
    - 사이킷런은 GridSearchCV API를 이용해 분류나 회귀같은 알고리즘에 사용되는 최적의 파라미터 도출 방안 제공
    - 상대적으로 오래걸림

#### * GridSearchCV 이용하여 결정 트리 알고리즘의 여러 가지 최적화 파라미터를 순차적으로 적용해 붓꽃 데이터 예측

In [46]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

# 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [48]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 tarin, test set fold로 나누어 테스트 수행 설정
## refit=True가 false임. -> True면 가장 좋은 파라미터 설정으로 재학습시킴

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid 의 파이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [49]:
# 최적 하이퍼 파라미터의 값과 그때의 정확도
print('GridSearchCV 최적 파라미터: ', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터:  {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [51]:
### 앞에서 tarin_test_split()으로 분리한 테스트 데이터 세트에 대해 예측하고 성능 평가
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도:0.9667


## 4. 데이터 전처리

### 4-1) 데이터 인코딩 : 레이블 인코딩, 원-핫 인코딩

#### * 레이블 인코딩: 카테고리 피처를 코드형 숫자 값으로 변환하는 것
    - TV, 냉장고, 전자레인지, 컴퓨터 ==> TV:1, 냉장고:2, 전자레인지:3, 컴퓨터:4
    - LabelEncoder 클래스로 구현. 객체 생성 후 fit(), transform() 호출해 레이블 인코딩 수행

In [55]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '컴퓨터']

# LabelEncoder를 객체로 생성 후 fit(), transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 3 4 2 2 4]


In [56]:
# 문자열 어떤 값이 어떤 숫자 값으로 인코딩됐는지 확인 : classes_
print('인코딩 클래스:', encoder.classes_)

# 인코딩값 다시 디코딩 : inverse_transform
print('디코딩 원본값:', encoder.inverse_transform([4,2,0,1,1,3,3]))

인코딩 클래스: ['TV' '냉장고' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['컴퓨터' '선풍기' 'TV' '냉장고' '냉장고' '전자레인지' '전자레인지']


#### * 원-핫 인코딩: 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 0표시
    - 레이블 인코딩의 할당 숫자 가중치로 인식되는 문제 해결
    - 해당 고유 값에 매칭되는 피처만 1이 되고 나머지 피처는 0입력.
    - OneHotEncoder 클래스 : 모든 문자열 값 숫자형 값으로 변환돼야함 & 입력값으로 2차원 데이터 필요

#### * 각 칼럼 TV0, 냉장고1, 믹서2, 선풍기3, 전자레인지4, 컴퓨터5

In [59]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


#### * 판다스 원-핫 인코딩 - 문자열 숫자형으로 변환할 필요 없음

In [60]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 4-2) 피처 스케일링과 정규화
    # 1 일반적인 의미의 표준화와 정규화 -> <피처 스케일링>
            - 표준화: 평균0, 분산1인 가우시안 정규 분포 가진 값으로 변환
            - 정규화: 서로 다른 피처의 크기를 동일하게 만들기 위함
    # 2 선형대수 개념의 정규화 -> <벡터 정규화>

### 4-3) StandardScaler : 피처 스케일링 클래스(표준화)

In [61]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트 로딩하고 df로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [64]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()
# StandardScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환돼 이를 df로 반환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### 4-4) MinMaxScaler : 피처 스케일링 클래스(정규화)

In [66]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler 로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 NumPy ndarray 로 반환돼 이를 df로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)   -1.870024
sepal width (cm)    -2.433947
petal length (cm)   -1.567576
petal width (cm)    -1.447076
dtype: float64

feature들의 최댓값
sepal length (cm)    2.492019
sepal width (cm)     3.090775
petal length (cm)    1.785832
petal width (cm)     1.712096
dtype: float64


### 4-5) 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

## 5. 사이킷런으로 수행하는 타이타닉 생존자 예측